networks:
  laravel:

services:
    nginx:
        image: nginx:1.23-alpine
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./src/public:/var/www/public
        ports:
            - 80:80
        container_name: nginx
        networks:
            - laravel

    php:
        container_name: ca-l-php
        build: ./docker/php
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        env_file:
           - .env
        networks:
            - laravel
    
    mysql:
        container_name: ca-l-mysql
        image: mysql:8
        env_file:
           - .env
        volumes:
            - ./docker/mysql/data/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - laravel
    
    npm:
        image: node:17
        container_name: npm
        working_dir: /var/www/
        volumes:
            - ./src:/var/www/
        ports:
            - 3001:3001
        entrypoint: ["/bin/sh", "-c", "chmod -R 777 . && npm install && npm run dev"]
        networks:
            - laravel


    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        networks:
            - laravel
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: wurstmeister/kafka:latest
        container_name: kafka
        networks:
            - laravel
        ports:
            - "9093:9093"
        expose:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        depends_on:
            - zookeeper

    # consumer:
    #     build: ./docker/python
    #     container_name: consumer
    #     working_dir: /pyrepl/
    #     volumes:
    #         - ./pyrepl:/pyrepl
    #     ports:
    #         - 3003:3003
    #     entrypoint: ["python", "consume.py"]
    #     restart: always
    #     depends_on:
    #         - zookeeper
    #         - kafka
    #     networks:
    #         - laravel

    publisher:
        build: ./docker/python
        container_name: publisher
        working_dir: /pyrepl/
        volumes:
            - ./pyrepl:/pyrepl
        ports:
            - 3002:3002
        entrypoint: ["python", "publish.py"]
        restart: always
        depends_on:
            - zookeeper
            - kafka
            # - consumer
        networks:
            - laravel